### ISSUE TITLE
overriding method counts as new visibility

### ISSUE THREAD

**Issue by erwan-joly** [pushpay-labs/semantic-versioning-analyzer#45]
when overriding a method we get 
``` (Minor) Class.Method(Object) is new or has been made accessible.```
The method was already accessible before it's just overridden so it should be a patch

**Comment by chris-findlay** [comment]
Is it tho?  Extending the API is a feature isn't it?  Even if the addition is only an override, it's still a widening, thus feature, thus minor?

**Comment by gregsdennis** [comment]
The API landscape doesn't change for an override.  Usually this will be a patch.

If the change alters the behavior significantly, the dev can make the bump a minor, but it should be patch by default for this tool.

The change that prompted this issue updated the content of a returned string.  One _could_ argue that warrants a breaking change, but that's overkill, and so is a minor bump.
