### ISSUE TITLE
error when using nuget feed from Azure Devops Server

### ISSUE THREAD

**Issue by PainElemental** [pushpay-labs/semantic-versioning-analyzer#57]
I have specified the URL to the nuget feed of our Azure DevOps Server in the config.json,
but when running the "analyze-semver" command, I get error repsonse that starts like this:

`An error has current processing your request:

- Error retrieving Nuget feed:

<!DOCTYPE html>
<html>
    <head>
        <title>TF400813: Resource not available for anonymous access. Client authentication required. - Azure DevOps Server</title>`

Is there a way to solve this?

**Comment by williamdenton** [comment]
looks like the code tries to access the feed here, you could try modifying this to see if you can add authentication to the http client. 

https://github.com/pushpay-labs/semantic-versioning-analyzer/blob/38f4ed42c0e79a905bb8974b1084bfb8b55ba162/source/SemVerAnalyzer/Nuget/NugetClient.cs#L38

It looks likes Nuget.Config file supports embedded credentials (though this seems like a bad idea to have in source control) so the client above could be extended to leverage these properties
https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials

**Comment by PainElemental** [comment]
When pushing a package to our feed on cmd, I always have to specify an ApiKey, e.g.

> nuget push -Source "MyCompany-NuGet" -ApiKey AzureDevOps "c:\MyPackage.nupkg"

But I don't see how this can be specified for the HttpRequestMessage in GetUrlContents :(

**Comment by PainElemental** [comment]
I replaced the NugetClient with a version that uses the library 'nuget.protocol'
https://www.nuget.org/packages/NuGet.Protocol/

This works fine with the Azure Feed :)

**Comment by Sam13** [comment]
Maybe this could be used as prerequisite for #58 ?
